### ISSUE TITLE
What's the difference between Jerryscript and Escargot?

### ISSUE THREAD

**Issue by lizhengxing-1** [pando-project/escargot#123]
I came across escargot and found its code is very neat and follows the ECMA262 v6 strictly.

My questions is:
What's the difference between escargot and Jerryscript?

Thanks!

**Comment by LaszloLango** [comment]
See: #94

**Comment by lizhengxing-1** [comment]
@LaszloLango  Thanks!

Why not put this information into Escargot project's README file?  I think It helps the people who know Escargot project at the first time.

Thanks!
