### ISSUE TITLE
Question about ES6 features

### ISSUE THREAD

**Issue by Achie72** [pando-project/escargot#129]
#51 seems to be aimed to expand escargot with ES6 features. By looking at the code i found, that it has guards for some of these, for example:
`ESCARGOT_ENABLE_PROXY_REFLECT`, `ESCARGOT_ENABLE_TYPEDARRAY`

As i'm about to start to contribute in this field, i wanted to ask if you have a plan for guard groups, or just to have a separate guard for all of them?

To draw a parallel to a similar project, JerryScript has a `CONFIG_DISABLE_ES2015` to turn on/off all features, and has one for all major ones, like: `CONFIG_DISABLE_ES2015_CLASS`, `CONFIG_DISABLE_REGEXP_BUILTIN` etc... 
As Escargot is aimed at mid-range devices, i'm not so sure if the project needs the smaller ones, but what about a big one, like a `ENABLE_ES2015`? I wanted to ask you about your opinion in the topic before first diving into the code, and adding unnecessary guards. Any plans, ideas?
(edit: just correction of myself)

**Comment by clover2123** [comment]
We have a plan to switch to the ES6 completely. The two macros (`ESCARGOT_ENABLE_PROXY_REFLECT`, `ESCARGOT_ENABLE_TYPEDARRAY`) are temporal guards now, and these will be removed when ES6 features are updated completely. 
According to that, we don't have to guard each ES6 features. But some features which have conflict with ES5.1 spec, we have to guard it with `ESCARGOT_ENABLE_ES2015` as represented in [#107 ](https://github.com/pando-project/escargot/pull/107), 

BTW, it is better to share our development plans of ES6 to avoid any conflicts. First of all, I'm currently working on TypedArray features. If you have any ideas or questions please feel free to contact me. Thank you.

**Comment by yichoi** [comment]
I encourage you to start with https://github.com/pando-project/escargot/issues/51 first

**Comment by yichoi** [comment]
Closing. please continue to further discussion at #51
