### ISSUE TITLE
Build & Test Issue

### ISSUE THREAD

**Issue by clover2123** [pando-project/escargot#13]
#### Build based on Make or Ninja via cmake
We've moved to ninja based build & test system.
But make (Makefile) based build & test is also available. 
You can freely choose one of them based on your comfort.

#### Travis CI fail
v8's regress-394673.js failed sometimes due to out-of-memory (too many recursive function calls. other JS engine, e.g. JSC, also failed running this TC).
So, the latest commit(#f3f0fdd) excludes this TC.

**Comment by yichoi** [comment]
If ``ninja`` is supported in Travis and show better performance than makefile, I would like to support only ``ninja`` in order not to get distracted.

**Comment by clover2123** [comment]
Now, ```ninja``` is used as default build system. Whole TCs are run by python script.
