### ISSUE TITLE
Follow up submodule updates #121

### ISSUE THREAD

**Issue by yichoi** [pando-project/escargot#143]

**Comment by yichoi** [comment]
@pmarkee

**Comment by pmarkee** [comment]
Update: #141 has landed, so we now have the `class` keyword. The tests for #121 are still failing because they also require inheritance, which is not implemented yet, but will be in progress soon AFAIK.

**Comment by pmarkee** [comment]
@yichoi it seems that vendortests for other patches (for example #157 #161 #180 ) also depend on some es6 features that are not yet implemented (`let`, `const`, `extends`). I think we could collect all related cases under this issue and do the necessary submodule update later.
Also, should I revert https://github.com/pando-tests/js_vendor_tc/pull/3 ? It is going to keep failing for a long time and it could be a blocker for other submodule updates.

**Comment by clover2123** [comment]
I think some necessary features like `let`, `const` are not easy to implement quickly, so it seems better to revert pando-tests/js_vendor_tc#3 to update and use the recent verdortests.

**Comment by yichoi** [comment]
I see, I will remove pando-tests/js_vendor_tc#3 commit from the js_vendor_tc repo then update this submodule of escargot repo too.

**Comment by yichoi** [comment]
removed by #193
